### PR TITLE
added check to prevent access to an undefined index

### PR DESCRIPTION
**Pull request by sascha-mummert**
## PR Description
Added a check to prevent the access of an undefined index. 
The error occurs only if you run at error level E_ALL.

## Checklist
- [ X] I agree with the Code Contribution License Agreement in CONTRIBUTING.md

### CODE REVIEW

**Comment by pjam** [comment]
Thanks, I already had this bug and created a case with ID 00040270.

**Comment by pjam** [comment]
Actually, @sascha-mummert fix will not work properly. What comes in `$matchingSuperAttributesIndexedByKeys[$key]` is an entity, but I think what we want to have in `$filteredSuperAttributes[$key]` is the actual value of the attribute.

Like this, for me, it was saving `{"some_super_attribute":[{}]}` in the super_attribute column.

I don't understand why this change was implemented like this in this update...

**Comment by dereuromark** [comment]
It shows that there should be a test case along with this change, just to make sure and also to prevent other changes to cause regressions in the future.

**Comment by sascha-mummert** [comment]
The test must be developed from another one, because I have problems by setting up the Project to be able to do it and have not the time to solve it.
But I tested the current code in our Project and it works like expected. And yes you were right that the code before had problems.

**Comment by sascha-mummert** [comment]
Mit der Version 1.8.0 wurde der Bug behoben

**Pull request closed without merging**
